SELECT orderdate, ROUND(sum(subtotal),0) AS dailysalesvalue
	FROM(
	SELECT
	SALES.SALESORDERDETAIL.salesorderid,
	SALES.SALESORDERDETAIL.salesorderdetailid,
	SALES.SALESORDERDETAIL.PRODUCTID,
	PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTCATEGORYID,
	PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID,
	orderqty,
	unitprice,
	(orderqty*unitprice) AS subtotal,
	SALES.SALESORDERHEADER.territoryid,
	SALES.SALESTERRITORY.NAME,
	orderdate
FROM SALES.SALESORDERDETAIL

FULL OUTER JOIN SALES.SALESORDERHEADER ON
	SALES.SALESORDERDETAIL.SALESORDERID = SALES.SALESORDERHEADER.SALESORDERID
	
FULL OUTER JOIN SALES.SALESTERRITORY ON
	SALES.SALESTERRITORY.TERRITORYID = SALES.SALESORDERHEADER.TERRITORYID
	
JOIN PRODUCTION.PRODUCT ON
	SALES.SALESORDERDETAIL.PRODUCTID = PRODUCTION.PRODUCT.PRODUCTID
	
JOIN PRODUCTION.PRODUCTSUBCATEGORY ON
	PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID = PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTSUBCATEGORYID) AS composite


WHERE PRODUCTCATEGORYID IN(1, 2) --Limits to Bike and Component categories

GROUP BY orderdate

ORDER BY dailysalesvalue DESC

LIMIT 50