--Avg lead time of items ordered where values are not null

SELECT 
    c.productid,
    PV.AverageLeadTime
	
FROM (
    SELECT
        SALES.SALESORDERDETAIL.salesorderid,
        SALES.SALESORDERDETAIL.salesorderdetailid,
        SALES.SALESORDERDETAIL.PRODUCTID,
        PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTCATEGORYID,
        PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID,
        production.productcategory.name AS categoryname,
        production.productsubcategory.name AS subcategoryname,
        orderqty, 
        unitprice,
        (orderqty * unitprice) AS subtotal,
        SALES.SALESORDERHEADER.territoryid,
        SALES.SALESTERRITORY.NAME AS territoryname,
        orderdate
    FROM SALES.SALESORDERDETAIL
    FULL OUTER JOIN SALES.SALESORDERHEADER ON
        SALES.SALESORDERDETAIL.SALESORDERID = SALES.SALESORDERHEADER.SALESORDERID
    FULL OUTER JOIN SALES.SALESTERRITORY ON
        SALES.SALESTERRITORY.TERRITORYID = SALES.SALESORDERHEADER.TERRITORYID
    JOIN PRODUCTION.PRODUCT ON
        SALES.SALESORDERDETAIL.PRODUCTID = PRODUCTION.PRODUCT.PRODUCTID
    JOIN PRODUCTION.PRODUCTSUBCATEGORY ON
        PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID = PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTSUBCATEGORYID
    JOIN PRODUCTION.productcategory ON 
        production.productcategory.productcategoryid = PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTCATEGORYID
) as c

LEFT JOIN Purchasing.ProductVendor AS PV
    ON PV.ProductID = c.ProductID
	
WHERE c.PRODUCTSUBCATEGORYID IN (1, 2, 3, 12, 14, 16)
	AND PV.averageleadtime IS NOT NULL