--Relevant items made in house

SELECT DISTINCT PRODUCTSUBCATEGORY.name FROM production.product

LEFT JOIN PRODUCTION.PRODUCTSUBCATEGORY ON
	PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID = PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTSUBCATEGORYID


WHERE PRODUCTSUBCATEGORY.productsubcategoryid IN (1,2,3,12,14,16)

ORDER BY productsubcategory.name