--Number of bikes and frames not made in house

SELECT COUNT(*) FROM production.product

LEFT JOIN PRODUCTION.PRODUCTSUBCATEGORY ON
	PRODUCTION.PRODUCT.PRODUCTSUBCATEGORYID = PRODUCTION.PRODUCTSUBCATEGORY.PRODUCTSUBCATEGORYID


WHERE PRODUCTSUBCATEGORY.productsubcategoryid IN (1,2,3,12,14,16)
	AND product.makeflag = FALSE